import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Head from "next/head";
import Navbar from "@/components/navbar/Navbar";
import "./layout.scss"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Real Estate",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
		<html lang="en">
			<Head>
				<link rel="icon" type="image/svg+xml" href="/favicon.png" />
				<meta name="description" content="Buy, Sell and Rent Properties" />
				<link
					href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,100;0,300;0,400;0,700;0,900;1,100;1,300;1,400;1,700;1,900&display=swap"
					rel="stylesheet"
				/>
			</Head>
			<body className={inter.className}>
				<div className="layout">
					<div className="navbar">
						<Navbar />
					</div>
					<div className="content">
						{children}
					</div>
				</div>
			</body>
		</html>
	);
}
